#pragma config(Sensor, in2,    liftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  encoderL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderR,         sensorQuadEncoder)
#pragma config(Motor,  port2,           driveL1,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Pivot,         tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           driveR1,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveR2,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           driveL2,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           driveL3,       tmotorVex393TurboSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "./autoHelper.c"

void pre_auton () {
	liftInit (0.35, 0.4, 0.04, 20, 100, liftPot);
	setLiftMotors (lift1, lift2);

	driveInit (0.5, 0.05, 0.005, 20, 100, encoderL, encoderR);
	setLeftDriveMotors (driveL1, driveL2, driveL3);
	setRightDriveMotors (driveR1, driveR2);
}

task autonomous () {
	driveTurnLeft (370, 50);
}

task usercontrol () {

}
