#pragma config(Sensor, in2,    liftPot,        sensorPotentiometer)
#pragma config(Motor,  port3,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lift2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "../libPID/NERD_PID.c"
#include "../libToolkit/Truespeed.h"

PID armPID;

float
overSample (int nBits, int sensorPort) {
	if (nBits > 0) {
		float sampleAverage = 0;

		for (int i = 0; i < pow (4, nBits); ++i)
			sampleAverage += SensorValue (sensorPort);

		return sampleAverage / (float) pow (4, nBits);
	}

	else
		return SensorValue (sensorPort);
}

void
driveLift (int speed) {
	int out = sgn(speed) * TrueSpeed[abs(speed)];
	motor[port3] = out;
	motor[port6] = out;
}

void pre_auton () {
	pidInit (armPID, 0.35, 0.3, 0.01, 25, 125);
}

task autonomous () {
}

task usercontrol () {
  while (true) {
  	float sensorPot = overSample(2, in2);
  	datalogAddValue (0, sensorPot);

  	float out = pidCalculate(armPID, 1580, sensorPot);
  	driveLift(out);

  	delay(1);
  }
}
