#pragma config(Sensor, in2,    gyrosensor,     sensorAnalog)
#pragma config(Sensor, dgtl1,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderR,       sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "../libGyro/NERD_Gyro.c"

Gyro gyro;

/**
 * Calibrate gyro and initialize PID controller
 */
void
pre_auton(){
	//Allow gyro to settle and then init/calibrate (Takes a total of around 2 seconds)
	delay(1100);
	gyroInit(gyro, in4);

	SensorValue[encoderL] = 0;
	SensorValue[encoderR] = 0;
}

task
autonomous(){
}

float fGyroAngle;

task
usercontrol(){
	long liTimer = nPgmTime;
	long printTimer = nPgmTime;
	fGyroAngle = 0;
	while (true) {
		float fDeltaTime = (nPgmTime - liTimer) / 1000.0;
		liTimer = nPgmTime;

		fGyroAngle += gyroGetRate(gyro)* fDeltaTime;

		if (nPgmTime - printTimer >= 100) {
			printTimer = nPgmTime;
			writeDebugStream ("Angle: %0.4f\tEncoderL: %d\tEncoderR: %d\n", fGyroAngle, SensorValue[encoderL], SensorValue[encoderR]);
		}

		delay (1);
	}
}
